language: python
env:
  - TEST_MODE=run_program
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install: .travis/install.sh
script: .travis/test.sh
matrix:
  include:
    - python: "2.7"
      env: TEST_MODE=check_style
