os:
  - linux
#  - osx
language: python
sudo: false
env:
  - TEST_MODE=run_tests
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.5"
install: .travis/install.sh
script: .travis/test.sh
after_success: .travis/finish.sh
matrix:
  include:
    - os: linux
      python: "2.7"
      env: TEST_MODE=check_style
    - os: linux
      python: "2.7"
      env: TEST_MODE=coverage
